name: Deploy files to AWS S3

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to AWS S3
      run: make deploy-aws
